name: Docker Build

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    docker-build:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'gayfurcity'
        steps: [uses: gayfurcity/publish-to-ghcr@v1]
